bffbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

profiles/urls.py
from django.urls import path
from .views import ( 
    my_profile_view, 
    invites_received_view, 
    profiles_list_view, 
    invite_profiles_list_view, 
    ProfileDetailView,
    ProfileListView,
    send_invatation,
    remove_from_friends,
    accept_invatation,
    reject_invatation,
    searched_profile_view,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('searched/',searched_profile_view, name='s-view'),
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/acctept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
]

templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}

    {% if request.user.is_authenticated %}  
        <div class="ui raised very padded text container segment" style="background-color: black !important;">
            <p style="font-family: 'Nanum Brush Script', cursive;color:white;font-size:2rem;text-align:center;  ">
                Hello {{user}}
            </p>
            <hr>
            <p style="font-family: 'Nanum Brush Script', cursive;font-size:4rem; text-align:center; color:white">
                Welcome to <span style="color:goldenrod;">Polaroid</span>
            </p>


        </div>
    {% else %}
        <div class="ui raised very padded text container segment" style="background-color: black !important;">
            <p style="font-family: 'Nanum Brush Script', cursive;font-size:4rem; text-align:center; color:white">
                Welcome to <span style="color:goldenrod;">Polaroid</span>
            </p>
        </div>
        <div class="ui raised very padded text container segment" style="background-color: black !important;">
            <p style="font-family: 'Nanum Brush Script', cursive;font-size:4rem; text-align:center; color:white;vertical-align: middle !important;">
                Don't have an account?
                <br>
                Feel free to
                <span>
                    <a href="accounts/register/" style="color: purple;">Register</a>
                </span> 
            </p>
        </div>
        
    {% endif %}
<br>
</h1>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:main-post-view' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}


<div class="ui inverted segment menu">
  <div class="ui sticky container" style="width: 670px !important; height: 42.6px !important; left: 424.6px;">
    <a href="{{path_to_home}}" class=" item">
        <h3 style="font-family: 'Nanum Brush Script', cursive;font-size:3rem;color: goldenrod;">Polaroid</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Board
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>
             
        
            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui avatar image">&nbsp;
                 {{ request.user }}
            </a>

            <a href={% url 'logout' %} class="ui item">
                Logout
            </a>
        {% else %}
        <a href={% url 'login' %} class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>

<script>




</script>